export const DOMAIN_ERROR_CODES = Object.freeze({
  APPROVAL_INVALIDATED: 'APPROVAL_INVALIDATED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_VERSION_MISMATCH: 'APPROVAL_VERSION_MISMATCH',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  CLOCK_CONVERSION_ERROR: 'CLOCK_CONVERSION_ERROR',
  CLOCK_INPUT_INVALID: 'CLOCK_INPUT_INVALID',
  CLOCK_STATE_INVALID: 'CLOCK_STATE_INVALID',
  COMMAND_SCHEMA_INVALID: 'COMMAND_SCHEMA_INVALID',
  COMMAND_RECEIPT_INVALID: 'COMMAND_RECEIPT_INVALID',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  DUPLICATE_REGISTRY_ID: 'DUPLICATE_REGISTRY_ID',
  EVENT_APPEND_CONFLICT: 'EVENT_APPEND_CONFLICT',
  EVENT_SCHEMA_INVALID: 'EVENT_SCHEMA_INVALID',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  OUTBOX_STATE_INVALID: 'OUTBOX_STATE_INVALID',
  INVALID_DECIMAL: 'INVALID_DECIMAL',
  DECIMAL_RESULT_OUT_OF_RANGE: 'DECIMAL_RESULT_OUT_OF_RANGE',
  INVALID_ID: 'INVALID_ID',
  INVALID_IDENTITY_FACTS: 'INVALID_IDENTITY_FACTS',
  INVALID_QUANTITY_UNIT: 'INVALID_QUANTITY_UNIT',
  INVALID_RATE: 'INVALID_RATE',
  NON_FINITE_DECIMAL: 'NON_FINITE_DECIMAL',
  ORDERING_INPUT_INVALID: 'ORDERING_INPUT_INVALID',
  PROJECTION_ACCESS_DENIED: 'PROJECTION_ACCESS_DENIED',
  REPLAY_INTEGRITY_INVALID: 'REPLAY_INTEGRITY_INVALID',
  REPLAY_SEQUENCE_INVALID: 'REPLAY_SEQUENCE_INVALID',
  REPLAY_STATE_MISMATCH: 'REPLAY_STATE_MISMATCH',
  REGISTRY_ENTRY_NOT_FOUND: 'REGISTRY_ENTRY_NOT_FOUND',
  SCHEDULED_EVENT_CONFLICT: 'SCHEDULED_EVENT_CONFLICT',
  SCHEDULED_EVENT_NOT_DUE: 'SCHEDULED_EVENT_NOT_DUE',
  SCHEDULED_EVENT_NOT_FOUND: 'SCHEDULED_EVENT_NOT_FOUND',
  SCHEDULED_EVENT_ORDER_VIOLATION: 'SCHEDULED_EVENT_ORDER_VIOLATION',
  SCHEDULER_INPUT_INVALID: 'SCHEDULER_INPUT_INVALID',
  SCHEDULER_STATE_INVALID: 'SCHEDULER_STATE_INVALID',
  SCHEDULER_TRANSITION_INVALID: 'SCHEDULER_TRANSITION_INVALID',
  SETTLEMENT_MAPPING_INVALID: 'SETTLEMENT_MAPPING_INVALID',
  SERIALIZATION_REJECTED: 'SERIALIZATION_REJECTED',
  TRANSITION_EVIDENCE_INVALID: 'TRANSITION_EVIDENCE_INVALID',
  UNIT_MISMATCH: 'UNIT_MISMATCH',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
} as const);

export type DomainErrorCode =
  (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];

export class DomainError extends Error {
  readonly code: DomainErrorCode;

  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
  }
}
