export const DOMAIN_ERROR_CODES = Object.freeze({
  APPROVAL_INVALIDATED: 'APPROVAL_INVALIDATED',
  APPROVAL_REJECTED: 'APPROVAL_REJECTED',
  APPROVAL_VERSION_MISMATCH: 'APPROVAL_VERSION_MISMATCH',
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHORIZATION_DENIED: 'AUTHORIZATION_DENIED',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',
  DUPLICATE_REGISTRY_ID: 'DUPLICATE_REGISTRY_ID',
  INVALID_DECIMAL: 'INVALID_DECIMAL',
  INVALID_ID: 'INVALID_ID',
  INVALID_IDENTITY_FACTS: 'INVALID_IDENTITY_FACTS',
  INVALID_QUANTITY_UNIT: 'INVALID_QUANTITY_UNIT',
  INVALID_RATE: 'INVALID_RATE',
  NON_FINITE_DECIMAL: 'NON_FINITE_DECIMAL',
  PROJECTION_ACCESS_DENIED: 'PROJECTION_ACCESS_DENIED',
  REGISTRY_ENTRY_NOT_FOUND: 'REGISTRY_ENTRY_NOT_FOUND',
  SERIALIZATION_REJECTED: 'SERIALIZATION_REJECTED',
  UNIT_MISMATCH: 'UNIT_MISMATCH',
  VERSION_MISMATCH: 'VERSION_MISMATCH',
} as const);

export type DomainErrorCode =
  (typeof DOMAIN_ERROR_CODES)[keyof typeof DOMAIN_ERROR_CODES];

export class DomainError extends Error {
  readonly code: DomainErrorCode;

  constructor(code: DomainErrorCode, message: string) {
    super(message);
    this.name = 'DomainError';
    this.code = code;
  }
}
