#!/usr/bin/env python3
"""Generate the canonical V03 registry module from the V01 traced catalogs."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "packages/core/src/registries/fixed-catalog.ts"


def quoted(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def main() -> None:
    coverage = json.loads((ROOT / "requirements/coverage_families.json").read_text())
    fixed = json.loads((ROOT / "requirements/fixed_catalogs.json").read_text())

    engines = [entry for entry in coverage["entries"] if entry["kind"] == "engine"]
    offices = [entry for entry in coverage["entries"] if entry["kind"] == "office_family"]
    international = [entry for entry in coverage["entries"] if entry["kind"] == "international_subtype"]

    groups: list[tuple[str, list[dict[str, object]]]] = [
        (
            "ENGINE_ENTRIES",
            [
                {"id": entry["id"], "name": entry["name"], "sourceDocument": "MASTER"}
                for entry in engines
            ],
        ),
        (
            "OFFICE_ENTRIES",
            [
                {"id": entry["name"], "name": entry["name"], "sourceDocument": entry["source_document"]}
                for entry in offices
            ],
        ),
        (
            "COMMODITY_ENTRIES",
            [
                {"id": row[0], "unit": row[1], "sourceDocument": "MASTER"}
                for row in fixed["commodities"]["rows"]
            ],
        ),
        (
            "PRODUCTION_SECTOR_ENTRIES",
            [
                {"id": row[0], "productionChain": row[1], "sourceDocument": "MASTER"}
                for row in fixed["production_sectors"]["rows"]
            ],
        ),
        (
            "TECHNOLOGY_ENTRIES",
            [
                {"id": row[0], "domain": row[1], "name": row[2], "sourceDocument": "MASTER"}
                for row in fixed["technologies"]["rows"]
            ],
        ),
        (
            "PROJECT_ENTRIES",
            [
                {"id": f"PROJECT-{index:02d}", "category": row[0], "name": row[1], "sourceDocument": "MASTER"}
                for index, row in enumerate(fixed["projects"]["rows"], 1)
            ],
        ),
        (
            "INTERNATIONAL_ACTIVITY_ENTRIES",
            [
                {"id": entry["id"], "name": entry["name"], "sourceDocument": "MASTER"}
                for entry in international
            ],
        ),
    ]

    lines = [
        "// Generated by tools/build_core_registries.py from traced authoritative catalogs.",
        "// Registration is metadata only and never claims an Engine or feature is implemented.",
        "import { CanonicalRegistry } from './registry.js';",
        "",
        "export const REGISTRY_IMPLEMENTATION_STATUS = 'REGISTERED_NOT_IMPLEMENTED' as const;",
        "",
    ]
    for name, entries in groups:
        lines.append(f"export const {name} = Object.freeze({quoted(entries)}) as readonly RegistryCatalogEntry[];")
        lines.append("")
    lines.extend(
        [
            "export interface RegistryCatalogEntry {",
            "  readonly id: string;",
            "  readonly name?: string;",
            "  readonly unit?: string;",
            "  readonly domain?: string;",
            "  readonly category?: string;",
            "  readonly productionChain?: string;",
            "  readonly sourceDocument: string;",
            "}",
            "",
            "export const ENGINE_REGISTRY = new CanonicalRegistry('Engine Registry', ENGINE_ENTRIES);",
            "export const OFFICE_REGISTRY = new CanonicalRegistry('Office Registry', OFFICE_ENTRIES);",
            "export const COMMODITY_REGISTRY = new CanonicalRegistry('Commodity Registry', COMMODITY_ENTRIES);",
            "export const PRODUCTION_SECTOR_REGISTRY = new CanonicalRegistry('Production Sector Registry', PRODUCTION_SECTOR_ENTRIES);",
            "export const TECHNOLOGY_REGISTRY = new CanonicalRegistry('Technology Registry', TECHNOLOGY_ENTRIES);",
            "export const PROJECT_REGISTRY = new CanonicalRegistry('Project Registry', PROJECT_ENTRIES);",
            "export const INTERNATIONAL_ACTIVITY_REGISTRY = new CanonicalRegistry('International Activity Registry', INTERNATIONAL_ACTIVITY_ENTRIES);",
            "",
        ]
    )
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    main()
