// Generated by tools/build_core_registries.py from traced authoritative catalogs.
// Registration is metadata only and never claims an Engine or feature is implemented.
import { CanonicalRegistry } from './registry.js';

export const REGISTRY_IMPLEMENTATION_STATUS =
  'REGISTERED_NOT_IMPLEMENTED' as const;

export const ENGINE_ENTRIES = Object.freeze([
  {
    id: 'E01',
    name: 'Engine 01 · Time & Event Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E02',
    name: 'Engine 02 · Population Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E03',
    name: 'Engine 03 · Labour & Wage Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E04',
    name: 'Engine 04 · Education & Human Capital Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E05',
    name: 'Engine 05 · Healthcare Engine',
    sourceDocument: 'MASTER',
  },
  { id: 'E06', name: 'Engine 06 · Housing Engine', sourceDocument: 'MASTER' },
  {
    id: 'E07',
    name: 'Engine 07 · Public Safety Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E08',
    name: 'Engine 08 · Resource & Inventory Engine',
    sourceDocument: 'MASTER',
  },
  { id: 'E09', name: 'Engine 09 · Energy Engine', sourceDocument: 'MASTER' },
  {
    id: 'E10',
    name: 'Engine 10 · Production Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E11',
    name: 'Engine 11 · Technology & R&D Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E12',
    name: 'Engine 12 · Project & Infrastructure Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E13',
    name: 'Engine 13 · Household & Demand Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E14',
    name: 'Engine 14 · Fiscal & Treasury Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E15',
    name: 'Engine 15 · Banking & Monetary Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E16',
    name: 'Engine 16 · Trade, Contract & Global Market Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E17',
    name: 'Engine 17 · FX & International Finance Engine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'E18',
    name: 'Engine 18 · National Accounts, Risk & Scoring Engine',
    sourceDocument: 'MASTER',
  },
]) as readonly RegistryCatalogEntry[];

export const OFFICE_ENTRIES = Object.freeze([
  { id: 'CAPTAIN', name: 'CAPTAIN', sourceDocument: 'CAPTAIN' },
  { id: 'CENTRAL_BANK', name: 'CENTRAL_BANK', sourceDocument: 'CENTRAL_BANK' },
  { id: 'FINANCE', name: 'FINANCE', sourceDocument: 'FINANCE' },
  { id: 'TRADE', name: 'TRADE', sourceDocument: 'TRADE' },
  { id: 'INDUSTRY', name: 'INDUSTRY', sourceDocument: 'INDUSTRY' },
  { id: 'SOCIAL', name: 'SOCIAL', sourceDocument: 'SOCIAL' },
]) as readonly RegistryCatalogEntry[];

export const COMMODITY_ENTRIES = Object.freeze([
  { id: 'CRUDE_OIL', unit: 'barrel', sourceDocument: 'MASTER' },
  { id: 'NATURAL_GAS', unit: 'MMBtu', sourceDocument: 'MASTER' },
  { id: 'URANIUM', unit: 'tonne U', sourceDocument: 'MASTER' },
  { id: 'GRAIN', unit: 'tonne', sourceDocument: 'MASTER' },
  { id: 'IRON_ORE', unit: 'tonne', sourceDocument: 'MASTER' },
  { id: 'COPPER', unit: 'tonne', sourceDocument: 'MASTER' },
  { id: 'LITHIUM', unit: 'tonne LCE', sourceDocument: 'MASTER' },
  { id: 'STEEL', unit: 'tonne', sourceDocument: 'MASTER' },
  { id: 'REFINED_FUEL', unit: 'barrel equivalent', sourceDocument: 'MASTER' },
  { id: 'MACHINERY', unit: 'equipment unit', sourceDocument: 'MASTER' },
  {
    id: 'SEMICONDUCTORS',
    unit: 'standardised chip unit',
    sourceDocument: 'MASTER',
  },
  { id: 'BATTERIES', unit: 'MWh-equivalent', sourceDocument: 'MASTER' },
]) as readonly RegistryCatalogEntry[];

export const PRODUCTION_SECTOR_ENTRIES = Object.freeze([
  {
    id: 'OIL_EXTRACTION',
    productionChain:
      'Developed Oil Reserve + Electricity + Labour + Machinery → Crude Oil',
    sourceDocument: 'MASTER',
  },
  {
    id: 'GAS_EXTRACTION',
    productionChain:
      'Developed Gas Reserve + Electricity + Labour + Machinery → Natural Gas',
    sourceDocument: 'MASTER',
  },
  {
    id: 'URANIUM_MINING',
    productionChain:
      'Developed Uranium Reserve + Electricity + Labour + Machinery → Uranium',
    sourceDocument: 'MASTER',
  },
  {
    id: 'IRON_ORE_MINING',
    productionChain:
      'Developed Iron Ore Reserve + Electricity + Labour + Machinery → Iron Ore',
    sourceDocument: 'MASTER',
  },
  {
    id: 'COPPER_MINING',
    productionChain:
      'Developed Copper Reserve + Electricity + Labour + Machinery → Copper',
    sourceDocument: 'MASTER',
  },
  {
    id: 'LITHIUM_MINING',
    productionChain:
      'Developed Lithium Reserve + Electricity + Labour + Machinery → Lithium',
    sourceDocument: 'MASTER',
  },
  {
    id: 'STEEL',
    productionChain: 'Iron Ore + Energy + Labour + Machinery Capacity → Steel',
    sourceDocument: 'MASTER',
  },
  {
    id: 'REFINED_FUEL',
    productionChain:
      'Crude Oil + Energy + Labour + Refinery Capacity → Refined Fuel',
    sourceDocument: 'MASTER',
  },
  {
    id: 'BATTERY',
    productionChain:
      'Lithium + Copper + Electricity + Machinery + Battery Technology + Skilled Labour → Batteries',
    sourceDocument: 'MASTER',
  },
  {
    id: 'MACHINERY',
    productionChain:
      'Steel + Copper + Electricity + Manufacturing Technology + Skilled Labour → Machinery',
    sourceDocument: 'MASTER',
  },
  {
    id: 'SEMICONDUCTOR',
    productionChain:
      'Copper + Electricity + Machinery + Semiconductor Technology + High Skill Labour → Semiconductors',
    sourceDocument: 'MASTER',
  },
  {
    id: 'ELECTRICITY',
    productionChain:
      'Fuel/Resource + Generation Capacity + Labour + Grid → Delivered Electricity',
    sourceDocument: 'MASTER',
  },
]) as readonly RegistryCatalogEntry[];

export const TECHNOLOGY_ENTRIES = Object.freeze([
  {
    id: 'ENERGY_ADV_SOLAR',
    domain: 'Energy',
    name: 'Advanced Solar',
    sourceDocument: 'MASTER',
  },
  {
    id: 'ENERGY_GRID_STORAGE',
    domain: 'Energy',
    name: 'Grid-scale Storage',
    sourceDocument: 'MASTER',
  },
  {
    id: 'ENERGY_ADV_NUCLEAR',
    domain: 'Energy',
    name: 'Advanced Nuclear',
    sourceDocument: 'MASTER',
  },
  {
    id: 'ENERGY_SMART_GRID',
    domain: 'Energy',
    name: 'Smart Grid',
    sourceDocument: 'MASTER',
  },
  {
    id: 'ENERGY_GREEN_H2',
    domain: 'Energy',
    name: 'Green Hydrogen',
    sourceDocument: 'MASTER',
  },
  {
    id: 'MFG_AUTOMATION',
    domain: 'Manufacturing',
    name: 'Industrial Automation',
    sourceDocument: 'MASTER',
  },
  {
    id: 'MFG_ROBOTICS',
    domain: 'Manufacturing',
    name: 'Advanced Robotics',
    sourceDocument: 'MASTER',
  },
  {
    id: 'MFG_PRECISION',
    domain: 'Manufacturing',
    name: 'Precision Manufacturing',
    sourceDocument: 'MASTER',
  },
  {
    id: 'MFG_SMART',
    domain: 'Manufacturing',
    name: 'Smart Manufacturing',
    sourceDocument: 'MASTER',
  },
  {
    id: 'SEMI_BASIC',
    domain: 'Semiconductor',
    name: 'Basic Semiconductor',
    sourceDocument: 'MASTER',
  },
  {
    id: 'SEMI_ADV_FAB',
    domain: 'Semiconductor',
    name: 'Advanced Fabrication',
    sourceDocument: 'MASTER',
  },
  {
    id: 'SEMI_PACKAGING',
    domain: 'Semiconductor',
    name: 'Advanced Packaging',
    sourceDocument: 'MASTER',
  },
  {
    id: 'SEMI_HPC',
    domain: 'Semiconductor',
    name: 'High-performance Chips',
    sourceDocument: 'MASTER',
  },
  {
    id: 'RESOURCE_ADV_EXPLORATION',
    domain: 'Resources & Materials',
    name: 'Advanced Exploration',
    sourceDocument: 'MASTER',
  },
  {
    id: 'RESOURCE_ADV_MINING',
    domain: 'Resources & Materials',
    name: 'Advanced Mining',
    sourceDocument: 'MASTER',
  },
  {
    id: 'RESOURCE_EFFICIENT_REFINING',
    domain: 'Resources & Materials',
    name: 'High-efficiency Refining',
    sourceDocument: 'MASTER',
  },
  {
    id: 'RESOURCE_BATTERY_CHEM',
    domain: 'Resources & Materials',
    name: 'Battery Chemistry',
    sourceDocument: 'MASTER',
  },
  {
    id: 'RESOURCE_ADV_MATERIALS',
    domain: 'Resources & Materials',
    name: 'Advanced Materials',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INFRA_DIGITAL_NETWORK',
    domain: 'Infrastructure & Digital',
    name: 'Digital Industrial Network',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INFRA_AUTO_LOGISTICS',
    domain: 'Infrastructure & Digital',
    name: 'Automated Logistics',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INFRA_SMART_PORT',
    domain: 'Infrastructure & Digital',
    name: 'Smart Port',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INFRA_ADV_GRID_MGMT',
    domain: 'Infrastructure & Digital',
    name: 'Advanced Grid Management',
    sourceDocument: 'MASTER',
  },
]) as readonly RegistryCatalogEntry[];

export const PROJECT_ENTRIES = Object.freeze([
  {
    id: 'PROJECT-01',
    category: 'Resource',
    name: 'Oil Field Development',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-02',
    category: 'Resource',
    name: 'Gas Field Development',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-03',
    category: 'Resource',
    name: 'Uranium Mine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-04',
    category: 'Resource',
    name: 'Iron Ore Mine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-05',
    category: 'Resource',
    name: 'Copper Mine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-06',
    category: 'Resource',
    name: 'Lithium Mine',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-07',
    category: 'Energy',
    name: 'Gas Power Plant',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-08',
    category: 'Energy',
    name: 'Fossil Power Plant',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-09',
    category: 'Energy',
    name: 'Nuclear Power Plant',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-10',
    category: 'Energy',
    name: 'Solar Farm',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-11',
    category: 'Energy',
    name: 'Wind Farm',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-12',
    category: 'Energy',
    name: 'Grid Upgrade',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-13',
    category: 'Energy',
    name: 'Energy Storage Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-14',
    category: 'Industrial',
    name: 'Steel Mill',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-15',
    category: 'Industrial',
    name: 'Refinery',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-16',
    category: 'Industrial',
    name: 'Machinery Plant',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-17',
    category: 'Industrial',
    name: 'Semiconductor Fab',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-18',
    category: 'Industrial',
    name: 'Battery Gigafactory',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-19',
    category: 'Industrial',
    name: 'Industrial Park',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-20',
    category: 'Industrial',
    name: 'Special Economic Zone',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-21',
    category: 'Infrastructure',
    name: 'Deepwater Port',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-22',
    category: 'Infrastructure',
    name: 'Freight Railway',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-23',
    category: 'Infrastructure',
    name: 'National Power Grid',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-24',
    category: 'Infrastructure',
    name: 'Digital Backbone',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-25',
    category: 'Infrastructure',
    name: 'Logistics Hub',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-26',
    category: 'Infrastructure',
    name: 'Strategic Reserve Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-27',
    category: 'Research Infrastructure',
    name: 'National Research Centre',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-28',
    category: 'Research Infrastructure',
    name: 'Semiconductor Research Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-29',
    category: 'Research Infrastructure',
    name: 'Energy Research Centre',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-30',
    category: 'Research Infrastructure',
    name: 'Materials Research Centre',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-31',
    category: 'Social Infrastructure',
    name: 'Basic Education Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-32',
    category: 'Social Infrastructure',
    name: 'Vocational Education Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-33',
    category: 'Social Infrastructure',
    name: 'Higher Education Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-34',
    category: 'Social Infrastructure',
    name: 'Primary Care Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-35',
    category: 'Social Infrastructure',
    name: 'Hospital / Emergency Facility',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-36',
    category: 'Social Infrastructure',
    name: 'Public Housing',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-37',
    category: 'Social Infrastructure',
    name: 'Worker Housing',
    sourceDocument: 'MASTER',
  },
  {
    id: 'PROJECT-38',
    category: 'Social Infrastructure',
    name: 'Police / Emergency Facility',
    sourceDocument: 'MASTER',
  },
]) as readonly RegistryCatalogEntry[];

export const INTERNATIONAL_ACTIVITY_ENTRIES = Object.freeze([
  {
    id: 'INT-01',
    name: 'Commodity Supply Agreement',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-02', name: 'Technology Licence', sourceDocument: 'MASTER' },
  { id: 'INT-03', name: 'Foreign Direct Investment', sourceDocument: 'MASTER' },
  { id: 'INT-04', name: 'Sovereign Loan', sourceDocument: 'MASTER' },
  { id: 'INT-05', name: 'Infrastructure Finance', sourceDocument: 'MASTER' },
  {
    id: 'INT-06',
    name: 'Resource Development Agreement',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INT-07',
    name: 'Joint International Project',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INT-08',
    name: 'Preferential Trade Agreement',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-09', name: 'Free Trade Agreement', sourceDocument: 'MASTER' },
  {
    id: 'INT-10',
    name: 'Customs Cooperation Agreement',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INT-11',
    name: 'Sector Market Access Agreement',
    sourceDocument: 'MASTER',
  },
  {
    id: 'INT-12',
    name: 'Multilateral Economic Agreement',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-13', name: 'Reserve Swap', sourceDocument: 'MASTER' },
  { id: 'INT-14', name: 'Sanction Package', sourceDocument: 'MASTER' },
  { id: 'INT-15', name: 'Grant Aid', sourceDocument: 'MASTER' },
  { id: 'INT-16', name: 'Commodity Aid', sourceDocument: 'MASTER' },
  {
    id: 'INT-17',
    name: 'Emergency Concessional Loan',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-18', name: 'Emergency Supply Contract', sourceDocument: 'MASTER' },
  { id: 'INT-19', name: 'Technical Assistance', sourceDocument: 'MASTER' },
  {
    id: 'INT-20',
    name: 'Project Reconstruction Aid',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-21', name: 'International Tender', sourceDocument: 'MASTER' },
  {
    id: 'INT-22',
    name: 'Strategic Economic Partnership',
    sourceDocument: 'MASTER',
  },
  { id: 'INT-23', name: 'Trade Dispute Settlement', sourceDocument: 'MASTER' },
]) as readonly RegistryCatalogEntry[];

export interface RegistryCatalogEntry {
  readonly id: string;
  readonly name?: string;
  readonly unit?: string;
  readonly domain?: string;
  readonly category?: string;
  readonly productionChain?: string;
  readonly sourceDocument: string;
}

export const ENGINE_REGISTRY = new CanonicalRegistry(
  'Engine Registry',
  ENGINE_ENTRIES,
);
export const OFFICE_REGISTRY = new CanonicalRegistry(
  'Office Registry',
  OFFICE_ENTRIES,
);
export const COMMODITY_REGISTRY = new CanonicalRegistry(
  'Commodity Registry',
  COMMODITY_ENTRIES,
);
export const PRODUCTION_SECTOR_REGISTRY = new CanonicalRegistry(
  'Production Sector Registry',
  PRODUCTION_SECTOR_ENTRIES,
);
export const TECHNOLOGY_REGISTRY = new CanonicalRegistry(
  'Technology Registry',
  TECHNOLOGY_ENTRIES,
);
export const PROJECT_REGISTRY = new CanonicalRegistry(
  'Project Registry',
  PROJECT_ENTRIES,
);
export const INTERNATIONAL_ACTIVITY_REGISTRY = new CanonicalRegistry(
  'International Activity Registry',
  INTERNATIONAL_ACTIVITY_ENTRIES,
);
